version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: hasker_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hasker
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.88.64.2
  nginx:
    image: nginx:latest
    container_name: hasker_nginx
    build: ./nginx
    restart: on-failure
    build: .
    command: sh -c "python manage.py makemigrations &&
                        python manage.py migrate &&
                        gunicorn microservice_sample_app.wsgi:application --bind 0.0.0.0:${APP_PORT}"
    expose:
      - 8000
    ports:
        - 80:80
    volumes:
        - /etc/nginx/site-available:/etc/nginx/conf.d
        - /home/app/hasker/static/:/home/app/hasker/static/
    networks:
      vpcbr:
        ipv4_address: 10.88.64.3


volumes:
  redis:
    driver: local
  db:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.88.64.0/24
          gateway: 10.88.64.1