version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: hasker_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hasker
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.88.64.2

  nginx:
    container_name: hasker_nginx
    restart: on-failure
    volumes:
      - ./:/code
      - /sock:/sock
    build:
      context: .
      dockerfile: docker/docker_nginx.conf
    depends_on:
      - django
    ports:
      - 8080:8080
    networks:
      vpcbr:
        ipv4_address: 10.88.64.3


  django:
    restart: always
    container_name: hasker
    volumes:
      - ./:/code
      - /sock:/sock
    build:
      context: .
      dockerfile: docker/docker_django.conf
    depends_on:
      - db
    command: bash -c "python /code/hasker/manage.py migrate && uwsgi --ini /etc/uwsgi.ini"
    ports:
      - 8000:8000
    networks:
      vpcbr:
        ipv4_address: 10.88.64.5

volumes:
  db:
    driver: local

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.88.64.0/24
          gateway: 10.88.64.1
