version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: hasker_db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=hasker
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: hasker_nginx
    restart: on-failure
    volumes:
      - ./code:/code
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
      - django
    ports:
      - 8080:8080

  django:
    restart: always
    container_name: hasker
    volumes:
      - ./code:/code
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    depends_on:
      - db
    #command: uwsgi --ini /etc/uwsgi.ini
    command: uwsgi --ini /etc/uwsgi.ini
    #command: bash -c "python /code/hasker/manage.py collectstatic --noinput && python /code/hasker/manage.py migrate && python /code/hasker/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000

volumes:
  db:
    driver: local

